### ISSUE TITLE
Tutorial Uses 3.0.0

### ISSUE THREAD

**Issue by sdiemert** [clojurewerkz/neocons.docs#13]
Hi,

The tutorial/introduction for the library indicates that one should use `3.0.0` [see here](http://clojureneo4j.info/articles/getting_started.html#adding-neocons-dependency-to-your-project). 

However, this causes an authentication issue upon issuing queries and is reportedly fixed in `3.1.0-beta`, [see here] (https://github.com/michaelklishin/neocons/issues/73).

Clojars indicates the current version to use is `3.1.0` [see here](https://clojars.org/clojurewerkz/neocons). 

Initially (as a newcomer to this library) I used `3.0.0` and had authentication issues while running queries. Updated to `3.1.0` and things seem to be working again... Might be useful to update the tutorial site to use a later version?

**Comment by michaelklishin** [comment]
@sdiemert sure, feel free to submit a [pull request](https://github.com/clojurewerkz/neocons.docs/) :)

**Comment by sdiemert** [comment]
@michaelklishin, here you go [https://github.com/clojurewerkz/neocons.docs/pull/14](https://github.com/clojurewerkz/neocons.docs/pull/14).
